const arrayOfKeys = ['Abu Dhabi, United Arab Emirates',
'Adelaide, Australia',
'Ahmedabad, India',
'Alexandria, Egypt',
'Almaty, Kazakhstan',
'Amman, Jordan',
'Amsterdam, Netherlands',
'Ankara, Turkey',
'Athens, Greece',
'Auckland, New Zealand',
'Austin, TX, United States',
'Baku, Azerbaijan',
'Bangalore, India',
'Bangkok, Thailand',
'Banja Luka, Bosnia And Herzegovina',
'Barcelona, Spain',
'Beijing, China',
'Beirut, Lebanon',
'Belgrade, Serbia',
'Berlin, Germany',
'Bogota, Colombia',
'Boston, MA, United States',
'Brasov, Romania',
'Bratislava, Slovakia',
'Brisbane, Australia',
'Brno, Czech Republic',
'Brussels, Belgium',
'Bucharest, Romania',
'Budapest, Hungary',
'Buenos Aires, Argentina',
'Bursa, Turkey',
'Cairo, Egypt',
'Calgary, Canada',
'Cape Town, South Africa',
'Casablanca, Morocco',
'Chandigarh, India',
'Chennai, India',
'Chicago, IL, United States',
'Chisinau, Moldova',
'Cluj-Napoca, Romania',
'Colombo, Sri Lanka',
'Copenhagen, Denmark',
'Dallas, TX, United States',
'Delhi, India',
'Doha, Qatar',
'Dubai, United Arab Emirates',
'Dublin, Ireland',
'Durban, South Africa',
'Edmonton, Canada',
'Eindhoven, Netherlands',
'Frankfurt, Germany',
'Gdansk, Poland',
'Gothenburg, Sweden',
'Guadalajara, Mexico',
'Gurgaon, India',
'Hamburg, Germany',
'Hanoi, Vietnam',
'Helsinki, Finland',
'Ho Chi Minh City, Vietnam',
'Hong Kong, Hong Kong',
'Houston, TX, United States',
'Hyderabad, India',
'Iasi, Romania',
'Istanbul, Turkey',
'Izmir, Turkey',
'Jakarta, Indonesia',
'Jerusalem, Israel',
'Johannesburg, South Africa',
'Kathmandu, Nepal',
'Kaunas, Lithuania',
'Kharkiv, Ukraine',
'Kiev, Ukraine',
'Kolkata, India',
'Krakow (Cracow), Poland',
'Kuala Lumpur, Malaysia',
'Las Vegas, NV, United States',
'Lima, Peru',
'Lisbon, Portugal',
'Ljubljana, Slovenia',
'Lodz, Poland',
'London, United Kingdom',
'Los Angeles, CA, United States',
'Lviv, Ukraine',
'Madrid, Spain',
'Manila, Philippines',
'Melbourne, Australia',
'Mexico City, Mexico',
'Milan, Italy',
'Minsk, Belarus',
'Monterrey, Mexico',
'Montevideo, Uruguay',
'Montreal, Canada',
'Moscow, Russia',
'Mumbai, India',
'Munich, Germany',
'Nairobi, Kenya',
'New York, NY, United States',
'Noida, India',
'Novi Sad, Serbia',
'Novosibirsk, Russia',
'Odessa, Ukraine',
'Oslo, Norway',
'Ottawa, Canada',
'Panama City, Panama',
'Paris, France',
'Perth, Australia',
'Phoenix, AZ, United States',
'Plovdiv, Bulgaria',
'Podgorica, Montenegro',
'Portland, OR, United States',
'Porto, Portugal',
'Poznan, Poland',
'Prague, Czech Republic',
'Pune, India',
'Quito, Ecuador',
'Reykjavik, Iceland',
'Riga, Latvia',
'Rome, Italy',
'Rotterdam, Netherlands',
'Saint Petersburg, Russia',
'San Diego, CA, United States',
'San Francisco, CA, United States',
'San Jose, Costa Rica',
'Santiago, Chile',
'Santo Domingo, Dominican Republic',
'Sao Paulo, Brazil',
'Sarajevo, Bosnia And Herzegovina',
'Seattle, WA, United States',
'Seoul, South Korea',
'Shanghai, China',
'Singapore, Singapore',
'Skopje, Macedonia',
'Sofia, Bulgaria',
'Stockholm, Sweden',
'Sydney, Australia',
'Taipei, Taiwan',
'Tallinn, Estonia',
'Tashkent, Uzbekistan',
'Tbilisi, Georgia',
'Tel Aviv-Yafo, Israel',
'Thessaloniki, Greece',
'Timisoara, Romania',
'Tirana, Albania',
'Tokyo, Japan',
'Toronto, Canada',
'Tunis, Tunisia',
'Utrecht, Netherlands',
'Valencia, Spain',
'Vancouver, Canada',
'Varna, Bulgaria',
'Victoria, Canada',
'Vienna, Austria',
'Vilnius, Lithuania',
'Warsaw, Poland',
'Winnipeg, Canada',
'Wroclaw, Poland',
'Yekaterinburg, Russia',
'Yerevan, Armenia',
'Zagreb, Croatia',
'Zurich, Switzerland']